### ISSUE TITLE
Logging in a user before the tests are run

### ISSUE THREAD

**Issue by VPuscoci** [axemclion/perfjankie#11]
How can i pass the actions.login object to perfjankie from browser-perf in the grunt task? I want to login a user before the tests are run.

**Comment by axemclion** [comment]
@VPuscoci This is currently possible using the `preScript` or the `preScriptFile` options. Here is more [documentation](https://github.com/axemclion/browser-perf/wiki/Node-Module---API#prescript) about how to use those options. 

Here is [documentation](https://github.com/axemclion/browser-perf/wiki/FAQ#how-can-i-test-a-page-that-requires-login) of how to login user before tests are run. You can simply reuse the same example.
