### ISSUE TITLE
Actions option

### ISSUE THREAD

**Issue by thiagohk** [axemclion/perfjankie#13]
Hi, I'am trying to mesure the performance not only of the scrolling of the page. I know that browser-perf has the actions option where you can create custom actions. Is this option is available in perfjankie? If yes, how can I configure this?
Thanks,

**Comment by axemclion** [comment]
I am working on this.

**Comment by axemclion** [comment]
@thiagohk I added the change where you can perform add an `action` to the configuration. This is similar to the browser-perf `action` option, and here is more [documentation](https://github.com/axemclion/browser-perf/wiki/Node-Module---API#actions).
