### ISSUE TITLE
browsers firefox isnt working

### ISSUE THREAD

**Issue by Hsheepypx** [axemclion/perfjankie#14]
When im using this local.config.json:
{
	"browsers": [{
		"browserName": "firefox"
	}],
	"selenium": {
		"hostname": "localhost",
		"port": 4444
	},
	"couch": {
		"server": "http://localhost:5984",
		"username": "name",
		"pwd": "password",
		"database": "autotest"
	}
}
And run first
perfjankie -c local.config.json --only-update-site
then
perfjankie <website> --config-file=local.config.json --name nametest --suite namesuite
Then check:
http://localhost:5984/autotest/_design/site/index.html#/page-select
and click on nametest it says:
Error loading page

An error occured when trying to load this page.
Please refresh this page, or go back to the home page . 

Until i remove the last session out of my database i cant see my other results from chrome by example, i havent checked internet explorer.

**Comment by axemclion** [comment]
Can you try this again ? Do you still see this error ?

**Comment by Hsheepypx** [comment]
This is still the problem only if ill remove this line from the database document:
   "toJSON": "function toJSON() {\n    [native code]\n}",
Then i can see the results fps and network.
At Paint Cycle i get an Error: Could not plot graph due to error in data

**Comment by axemclion** [comment]
@Hsheepypx which database document has this issue? This looks like toJSON was serialized, where it should not have been. 

Is there a repro that i could use to debug?

**Comment by Hsheepypx** [comment]
I'll start the selenium server with:
	java -jar selenium-server-standalone-2.44.0.jar
Then ill use this code in another cmd
	perfjankie http://www.google.com --config-file=local.config.json --name google --suite google
This is my local.config.json 
```local.config.json 
{
	"browsers": [{
		"browserName": "firefox"
	}],
	"selenium": {
		"hostname": "localhost",
		"port": 4444
	},
	"couch": {
		"server": "http://localhost:5984",
		"username": "root",
		"pwd": "root",
		"database": "autotest"
	}
}
```
This is the document i get in my database wich gives the error
```Database
{
   "_id": "a117b22e8475b9ffee15603e2400327e",
   "_rev": "3-f6a2bacf6745a52096f37ee4131cce12",
   "url": "http://www.google.com",
   "data": {
       "numAnimationFrames": 20,
       "numFramesSentToScreen": 20,
       "droppedFrameCount": 4,
       "meanFrameTime": 16.53750568782802,
       "framesPerSec_raf": 60.46861109992076,
       "unloadEventEnd": 0,
       "responseEnd": 1421832199362,
       "responseStart": 1421832199334,
       "unloadEventStart": 0,
       "domainLookupEnd": 1421832198705,
       "domInteractive": 1421832199434,
       "domContentLoadedEventStart": 1421832199489,
       "domComplete": 1421832201128,
       "domainLookupStart": 1421832198705,
       "redirectEnd": 0,
       "redirectStart": 0,
       "toJSON": "function toJSON() {\n    [native code]\n}",
       "connectEnd": 1421832198705,
       "connectStart": 1421832198705,
       "loadEventStart": 1421832201128,
       "navigationStart": 1421832198022,
       "requestStart": 1421832199159,
       "fetchStart": 1421832198705,
       "domContentLoadedEventEnd": 1421832199496,
       "domLoading": 1421832199335,
       "loadEventEnd": 1421832201131
   },
   "meta": {
       "_browserName": "firefox",
       "_url": "http://www.google.com"
   },
   "name": "google",
   "suite": "google",
   "browser": "firefox",
   "run": 1421832193286,
   "time": 1421832193286,
   "type": "perfData"
}
```
On http://localhost:5984/autotest/_design/site/index.html#/page-select
I click on google -> firefox
And this is what i get:
```
 Error loading page

An error occured when trying to load this page.
Please refresh this page, or go back to the home page . 
```
If i remove in the databasedocument the line with toJSON and refresh the page on perfjankie.
Then can see the fps, and network. 
Think there is also missing some data now?

Im using win7 pro with Firefox v35.0

![1 perfjankie with the test](https://cloud.githubusercontent.com/assets/2099839/5833875/0712b592-a158-11e4-81fd-d5bf0468ce7f.png)
![2 when clicked on firefox](https://cloud.githubusercontent.com/assets/2099839/5833873/070fbdba-a158-11e4-9a7f-966acf3aad40.png)
![3 after remove tojson](https://cloud.githubusercontent.com/assets/2099839/5833876/071dd850-a158-11e4-9429-f5695f3a0cd1.png)

**Comment by axemclion** [comment]
@Hsheepypx Thanks for reporting this. I updated the views for fix this. Please re-open the bug if this still does not fix the issue. This is in the latest 1.1.2 version of perfjankie.
