### ISSUE TITLE
Layout and Recalculate styles not working

### ISSUE THREAD

**Issue by arschmitz** [axemclion/perfjankie#23]
Graphs do not work on some pages / runs but do on others no differences in the runs or output not errors.

**Comment by axemclion** [comment]
This usually is an issue when numbers for these are missing. I am still thinking if I should call these numbers zero and draw a graph, or say that data is not available. 

Is there a page I can test this on ?Do you know if that page is infact generating layouts/recalculate styles?

**Comment by axemclion** [comment]
Closing this issue as it has been inactive for a while, and there is no action on this. `browser-perf`, the underlying system that collects data has improved to give us much more data, so this should be solved.

If you think that this problem still exists, please reopen the issue.
