### ISSUE TITLE
Running Perf Jankie launches Chrome.exe 

### ISSUE THREAD

**Issue by AtulUjjwal** [axemclion/perfjankie#29]
When i try to run Perf jankie, it launches chrome browser along with chrome.exe.
And the page which i am trying to test is not loaded.

**Comment by AtulUjjwal** [comment]
And it gives following error message : 

Error: [init({"browserName":"chrome","chromeOptions":{"perfLoggingPrefs":{"traceCategories":",blink.console,devtools.timeline,disabled-by-default-devtools.timeline,toplevel,disabled-by-default-devtools.timeline.frame,benchmark"}},"loggingPrefs":{"performance":"ALL"}})] The environment you requested was unavailable.
 Use --force to continue.

**Comment by axemclion** [comment]
Can you set the environment variable `export DEBUG=*` and paste the logs ? It would have much more information to diagnose the issue.
