### ISSUE TITLE
Getting error "The environment you requested was unavailable"

### ISSUE THREAD

**Issue by AtulUjjwal** [axemclion/perfjankie#30]
I am trying to run perfJankie and getting this error every time.

Code: 

var login = function(){
                    return browser.get('http://localhost:8081').then(function(){
                    return browser.setLocalStorageKey('jarvisMock','true')
            });
            }

perfjankie({
                suite: 'Performance analysis',
                name: "Test",
                run: "1.0",
                preScript: function(browser) {
                     return login();
                },
                time: new Date().getTime(),
                callback: function (err, res) {
                    if (err) {
                        throw err;
                    }
                    runQueue(i + 1);
                },
                repeat: 1,
                selenium: 'http://localhost:4444/wd/hub',
                couch: COUCH,
                browsers: [{
                    browserName: 'chrome',
                    chromeOptions: {
                        args: ['--start-maximized',"--enable-gpu-benchmarking"],
                    }
                }],
                metrics : ['TimelineMetrics','NetworkResources', 'NetworkTimings', 'RafRenderingStats','ChromeTracingMetrics'],
                actions: function (browser) {
                    if (job.component === 'HomePageRefesh') {
                        return browser.execute('chrome.gpuBenchmarking.smoothScrollBy(2000, function(){})').then(function(){
                        return browser.sleep(5000).then(function(){
                        return browser.refresh();
                        });
                        });
                    }
                    if (job.component === 'UpdatePageRefresh') {
                         return browser.get(job.url + '/index.html#/auth/updates/checkForUpdate').then(function(){
                         return browser.sleep(3000).then(function(){
                         return browser.execute('chrome.gpuBenchmarking.smoothScrollBy(2000, function(){})').then(function(){
                         return browser.sleep(5000).then(function(){
                         return browser.refresh();
                         });
                         });
                         });
                         });
                    }
                }
            });

Error logs:

Running "shell:perfjankie" (shell) task
selenium standalone is up to date.
chromedriver is up to date.
C:\XXX\node_modules\webdriver-manager\selenium\chromedriver_2.16.zip C:\XXX\node_modules\webdriver-manager\selenium
The following files were installed: C:\XXX\node_modules\webdriver-manager\selenium\selenium-server-standalone-2.46.0.jar C:\XXX\node_modules\webdriver-manager\selenium\chromedriver
selenium.pid: 832
Running [1/2] HomePageRefesh@923328
Wed, 20 Jan 2016 14:04:54 GMT bp:index Selenium is on localhost
Wed, 20 Jan 2016 14:04:54 GMT bp:metrics Initializing Metrics
Wed, 20 Jan 2016 14:04:54 GMT bp:probes Registering probe PerfLogProbe
Wed, 20 Jan 2016 14:04:54 GMT bp:probes:AndroidTracingProbe Initialize
Wed, 20 Jan 2016 14:04:54 GMT bp:probes Registering probe AndroidTracingProbe
Wed, 20 Jan 2016 14:04:54 GMT bp:probes Registering probe NetworkResourcesProbe
Wed, 20 Jan 2016 14:04:54 GMT bp:probes Registering probe NavTimingProbe
Wed, 20 Jan 2016 14:04:54 GMT bp:probes Registering probe RafBenchmarkingProbe
Wed, 20 Jan 2016 14:04:54 GMT bp:probes Registering probe PerfLogProbe
Wed, 20 Jan 2016 14:04:54 GMT bp:probes Registering probe AndroidTracingProbe
Wed, 20 Jan 2016 14:04:54 GMT bp:metrics TimelineMetrics setup called
Wed, 20 Jan 2016 14:04:54 GMT bp:metrics NetworkResources setup called
Wed, 20 Jan 2016 14:04:54 GMT bp:metrics ChromeTracingMetrics setup called
Wed, 20 Jan 2016 14:04:54 GMT bp:probes setup
Wed, 20 Jan 2016 14:04:54 GMT bp:probes PerfLogProbe setup called
Wed, 20 Jan 2016 14:04:54 GMT bp:probes AndroidTracingProbe setup called
Wed, 20 Jan 2016 14:04:54 GMT bp:probes NetworkResourcesProbe setup called
Wed, 20 Jan 2016 14:04:54 GMT bp:index Stating browser with {"browserName":"chrome","chromeOptions":{"args":["--start-maximized","--enable-gpu-benchmarking"],"perfLoggingPrefs":{"traceCategories":",blink.console,devtools.timeline,disabled-by-default-devtools.timeline,toplevel,disabled-by-default-devtools.timeline.frame,benchmark"}},"loggingPrefs":{"performance":"ALL"}}
Wed, 20 Jan 2016 14:04:54 GMT bp:selenium CALL init({"browserName":"chrome","chromeOptions":{"args":["--start-maximiz
Wed, 20 Jan 2016 14:04:56 GMT bp:selenium CALL quit()

C:\XXX\node_modules\perfjankie\node_modules\q\q.js:155
                throw e;
                ^
Error: [init({"browserName":"chrome","chromeOptions":{"args":["--start-maximized","--enable-gpu-benchmarking"],"perfLoggingPrefs":{"traceCategories":",blink.console,devtools.timeline,disabled-by-default-devtools.timeline,toplevel,disabled-by-default-devtools.timeline.frame,benchmark"}},"loggingPrefs":{"performance":"ALL"}})] The environment you requested was unavailable.

Have anyone faced this issue ?

**Comment by axemclion** [comment]
@AtulUjjwal, can you run this with just browser-perf and see if that works ?

**Comment by hypery2k** [comment]
the selenium grid is not available there. You use the node directly, see https://github.com/axemclion/browser-perf/issues/59

**Comment by axemclion** [comment]
Closing this issue, as this seems like a Browser-perf issue. 

@AtulUjjwal Please reopen this issue if it does not work.
